[package]
name = "grl-sources"
version = "0.2.1"
authors = ["Gaz Liddon"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow="1.0.75"
serde = { version="1.0.188", features=[ "derive" ], optional = true }
thiserror="1.0.48"

grl-utils = {path="../grl-utils"}

[features]
default = []
serde = ["dep:serde"]

[dev-dependencies]
pretty_assertions="1.4.0"
