[package]
name = "emu6809"
version = "0.1.0"
authors = ["Gaz Liddon"]
categories =["emulation", "motorola", "6809"]
edition = "2021"
build = "build.rs"
description = "In development 6809 emulator"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/gazliddon/crates"

[build-dependencies]
sha1 = {workspace=true}
bitflags={ workspace=true }
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
serde_json = "*"

[dependencies]
num="*"
byteorder="*"
sha1 = {workspace=true}
bitflags= {workspace=true}
lazy_static = {workspace=true}
thiserror={workspace=true}

serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
serde_json = "*"

log="*"
itertools = "*"

