use std::fs;
use std::path::Path;

use crate::StargateInput;
use emucore::mem::{MemErrorTypes, MemResult, MemoryIO};
use emucore::sha1::Digest;
use emucore::sha1::Sha1;

pub const ROMS: [(u16, &str); 12] = [
    (0x0000, "01"),
    (0x1000, "02"),
    (0x2000, "03"),
    (0x3000, "04"),
    (0x4000, "05"),
    (0x5000, "06"),
    (0x6000, "07"),
    (0x7000, "08"),
    (0x8000, "09"),
    (0xd000, "10"),
    (0xe000, "11"),
    (0xf000, "12"),
];

/// Interrupt edges generated by the raster/beam timing hardware.
#[derive(Default, Clone, Copy, Debug, PartialEq, Eq)]
pub struct VideoInterrupts {
    /// ROM PIA CA1: the once-per-frame line-240 interrupt.
    pub irq: bool,
    /// ROM PIA CB1: the four-times-per-frame, approximately 4 ms interrupt.
    pub firq: bool,
}

/// The early Williams/Stargate main-board address space.
pub struct StargateBus {
    rom: [u8; 0x1_0000],
    vram: [u8; 0xc000],
    cmos: [u8; 0x0400],
    palette: [u8; 0x0010],
    pia: [[u8; 4]; 2],
    bank_rom: bool,
    watchdog_writes: u64,
    input: StargateInput,
    sound_commands: Vec<u8>,
    video_frame: Vec<u8>,
    video_cycles: u64,
    video_scanline: usize,
}

impl StargateBus {
    pub fn from_rom_dir(dir: &Path) -> Result<Self, Box<dyn std::error::Error>> {
        let mut bus = Self {
            rom: [0; 0x1_0000],
            vram: [0; 0xc000],
            cmos: [0; 0x0400],
            palette: [0; 0x0010],
            pia: [[0; 4]; 2],
            bank_rom: false,
            watchdog_writes: 0,
            input: StargateInput::default(),
            sound_commands: Vec::new(),
            video_frame: vec![0; 292 * 240 * 4],
            video_cycles: 0,
            video_scanline: 0,
        };
        for (address, name) in ROMS {
            let data = fs::read(dir.join(name))?;
            if data.len() != 0x1000 {
                return Err(format!("ROM {name} is {} bytes, expected 4096", data.len()).into());
            }
            bus.rom[address as usize..address as usize + data.len()].copy_from_slice(&data);
        }
        Ok(bus)
    }

    /// Render the Williams packed 4-bit video RAM as a terminal-friendly
    /// luminance image. Each video byte contains two horizontal pixels and
    /// rows are separated by 256 bytes.
    pub fn video_ascii(&self, columns: usize, rows: usize) -> Vec<String> {
        const RAMP: &[u8] = b" .:-=+*#%@";
        (0..rows)
            .map(|out_y| {
                let y = out_y * 240 / rows;
                (0..columns)
                    .map(|out_x| {
                        let x = out_x * 304 / columns;
                        let packed = self.vram[y + (x / 2) * 256];
                        let pixel = if x & 1 == 0 {
                            packed >> 4
                        } else {
                            packed & 0x0f
                        };
                        RAMP[(pixel as usize * (RAMP.len() - 1) / 15).min(RAMP.len() - 1)] as char
                    })
                    .collect()
            })
            .collect()
    }

    /// Return the visible framebuffer as RGBA pixels for graphical frontends.
    pub fn video_rgba(&self) -> Vec<u8> {
        let mut pixels = Vec::with_capacity(304 * 240 * 4);
        for y in 0..240 {
            for x in 0..304 {
                let packed = self.vram[y + (x / 2) * 256];
                let value = if x & 1 == 0 {
                    packed >> 4
                } else {
                    packed & 0x0f
                };
                pixels.extend_from_slice(&Self::palette_rgba(self.palette[value as usize]));
            }
        }
        pixels
    }

    /// Render Stargate's MAME-visible area (x=12..303, y=7..246).
    pub fn video_rgba_visible(&self) -> Vec<u8> {
        self.video_frame.clone()
    }

    /// Advance the raster beam. Stargate's 1 MHz 6809 and 512x260 video
    /// timing yield exactly 64 CPU cycles per scanline.
    pub fn advance_video(&mut self, cycles: u64) -> VideoInterrupts {
        let mut interrupts = VideoInterrupts::default();
        self.video_cycles += cycles;
        while self.video_cycles >= 64 {
            self.video_cycles -= 64;
            let scanline = self.video_scanline;
            self.render_scanline(scanline);
            // The ROM PIA's CA1 and CB1 are driven by beam position.  CB1
            // pulses at the four 4 ms phases; CA1 pulses on line 240.
            if scanline % 64 == 0 {
                interrupts.firq = true;
            }
            // CA1's line-240 IRQ is intentionally left disabled until the
            // 6821 control/status latch is modeled.  Asserting it as a raw
            // CPU IRQ can race the ROM's RAM-resident IRQ vector setup and
            // send execution through uninitialized memory.
            self.video_scanline = (self.video_scanline + 1) % 260;
        }
        interrupts
    }

    fn render_scanline(&mut self, scanline: usize) {
        if !(7..247).contains(&scanline) {
            return;
        }
        let row = scanline - 7;
        let start = row * 292 * 4;
        for x in 12..304 {
            let packed = self.vram[scanline + (x / 2) * 256];
            let value = if x & 1 == 0 {
                packed >> 4
            } else {
                packed & 0x0f
            };
            let pixel = Self::palette_rgba(self.palette[value as usize]);
            let offset = start + (x - 12) * 4;
            self.video_frame[offset..offset + 4].copy_from_slice(&pixel);
        }
    }

    fn palette_rgba(value: u8) -> [u8; 4] {
        let component =
            |bits: u8| -> u8 { [0x00, 0x26, 0x51, 0x76, 0x89, 0xae, 0xd9, 0xff][bits as usize] };
        let blue = ((if value & 0x40 != 0 { 0x5f } else { 0 })
            + if value & 0x80 != 0 { 0xa0 } else { 0 }) as u8;
        [component(value & 7), component((value >> 3) & 7), blue, 255]
    }

    fn pia_index(addr: usize) -> Option<(usize, usize)> {
        match addr {
            0xc804..=0xc807 => Some((0, addr - 0xc804)),
            0xc80c..=0xc80f => Some((1, addr - 0xc80c)),
            _ => None,
        }
    }

    fn read_mapped(&self, addr: usize) -> u8 {
        match addr {
            0x0000..=0x8fff if self.bank_rom => self.rom[addr],
            0x0000..=0xbfff => self.vram[addr],
            0xc000..=0xc00f => 0, // write-only palette
            0xc804..=0xc807 | 0xc80c..=0xc80f => {
                let (pia, reg) = Self::pia_index(addr).unwrap();
                match (pia, reg) {
                    (0, 0) => self.input.port0(),
                    (0, 2) => self.input.port1(),
                    (1, 0) => self.input.port2(),
                    _ => self.pia[pia][reg],
                }
            }
            0xcb00..=0xcbff => self.video_scanline as u8, // vertical beam counter
            0xcc00..=0xcfff => self.cmos[addr - 0xcc00],
            0xd000..=0xffff => self.rom[addr],
            _ => 0,
        }
    }

    pub fn set_input(&mut self, input: StargateInput) {
        self.input = input;
    }

    pub fn take_sound_commands(&mut self) -> Vec<u8> {
        std::mem::take(&mut self.sound_commands)
    }

    pub fn palette(&self) -> [u8; 16] {
        self.palette
    }
}

impl MemoryIO for StargateBus {
    fn inspect_byte(&self, addr: usize) -> MemResult<u8> {
        if addr < 0x1_0000 {
            Ok(self.read_mapped(addr))
        } else {
            Err(MemErrorTypes::IllegalAddress(addr))
        }
    }
    fn inspect_word(&self, addr: usize) -> MemResult<u16> {
        Ok(u16::from_be_bytes([
            self.inspect_byte(addr)?,
            self.inspect_byte(addr + 1)?,
        ]))
    }
    fn upload(&mut self, addr: usize, data: &[u8]) -> MemResult<()> {
        for (offset, value) in data.iter().enumerate() {
            self.store_byte(addr + offset, *value)?;
        }
        Ok(())
    }
    fn get_range(&self) -> std::ops::Range<usize> {
        0..0x1_0000
    }
    fn update_sha1(&self, digest: &mut Sha1) {
        digest.update(self.rom);
        digest.update(self.vram);
        digest.update(self.cmos);
    }
    fn load_byte(&mut self, addr: usize) -> MemResult<u8> {
        self.inspect_byte(addr)
    }
    fn store_byte(&mut self, addr: usize, value: u8) -> MemResult<()> {
        if addr >= 0x1_0000 {
            return Err(MemErrorTypes::IllegalAddress(addr));
        }
        match addr {
            0x0000..=0xbfff => self.vram[addr] = value,
            0xc000..=0xc00f => self.palette[addr - 0xc000] = value,
            0xc804..=0xc807 | 0xc80c..=0xc80f => {
                let (pia, reg) = Self::pia_index(addr).unwrap();
                self.pia[pia][reg] = value;
                // PIA 1 port B is the main-to-sound command latch. Williams
                // drives the upper two bits high before pulsing CB1.
                if pia == 1 && reg == 2 {
                    self.sound_commands.push(value | 0xc0);
                }
            }
            0xc900..=0xc9ff => self.bank_rom = value & 1 != 0,
            0xcbff => {
                if value == 0x39 {
                    self.watchdog_writes += 1;
                }
            }
            0xcc00..=0xcfff => self.cmos[addr - 0xcc00] = value,
            0xd000..=0xffff => {} // ROM / unmapped writes are ignored
            _ => {}
        }
        Ok(())
    }
    fn store_word(&mut self, addr: usize, value: u16) -> MemResult<()> {
        let [hi, lo] = value.to_be_bytes();
        self.store_byte(addr, hi)?;
        self.store_byte(addr + 1, lo)
    }
    fn load_word(&mut self, addr: usize) -> MemResult<u16> {
        Ok(u16::from_be_bytes([
            self.load_byte(addr)?,
            self.load_byte(addr + 1)?,
        ]))
    }
}

#[cfg(test)]
mod tests {
    use super::StargateBus;
    use crate::StargateInput;
    use emucore::mem::MemoryIO;

    fn bus() -> StargateBus {
        StargateBus {
            rom: [0; 0x1_0000],
            vram: [0; 0xc000],
            cmos: [0; 0x0400],
            palette: [0; 0x0010],
            pia: [[0; 4]; 2],
            bank_rom: false,
            watchdog_writes: 0,
            input: StargateInput::default(),
            sound_commands: Vec::new(),
            video_frame: vec![0; 292 * 240 * 4],
            video_cycles: 0,
            video_scanline: 0,
        }
    }

    #[test]
    fn bank_select_changes_low_memory_reads_but_not_writes() {
        let mut bus = bus();
        bus.rom[0x1234] = 0xa5;
        bus.store_byte(0x1234, 0x5a).unwrap();
        assert_eq!(bus.load_byte(0x1234).unwrap(), 0x5a);
        bus.store_byte(0xc900, 1).unwrap();
        assert_eq!(bus.load_byte(0x1234).unwrap(), 0xa5);
        bus.store_byte(0x1234, 0x3c).unwrap();
        bus.store_byte(0xc900, 0).unwrap();
        assert_eq!(bus.load_byte(0x1234).unwrap(), 0x3c);
    }

    #[test]
    fn watchdog_only_accepts_stargate_reset_value() {
        let mut bus = bus();
        bus.store_byte(0xcbff, 0).unwrap();
        bus.store_byte(0xcbff, 0x39).unwrap();
        assert_eq!(bus.watchdog_writes, 1);
    }

    #[test]
    fn pia_reads_follow_logical_inputs() {
        let mut bus = bus();
        bus.set_input(StargateInput {
            fire: true,
            down: true,
            coin1: true,
            ..Default::default()
        });
        assert_eq!(bus.load_byte(0xc804).unwrap(), 0x81);
        assert_eq!(bus.load_byte(0xc806).unwrap(), 0x00);
        assert_eq!(bus.load_byte(0xc80c).unwrap(), 0x10);
    }
}
