use std::fs;
use std::path::Path;

use crate::StargateInput;
use emucore::mem::{MemErrorTypes, MemResult, MemoryIO};
use emucore::sha1::Digest;
use emucore::sha1::Sha1;

pub const ROMS: [(u16, &str); 12] = [
    (0x0000, "01"),
    (0x1000, "02"),
    (0x2000, "03"),
    (0x3000, "04"),
    (0x4000, "05"),
    (0x5000, "06"),
    (0x6000, "07"),
    (0x7000, "08"),
    (0x8000, "09"),
    (0xd000, "10"),
    (0xe000, "11"),
    (0xf000, "12"),
];

/// Interrupt edges generated by the raster/beam timing hardware.
#[derive(Default, Clone, Copy, Debug, PartialEq, Eq)]
pub struct VideoInterrupts {
    /// ROM PIA CA1: the once-per-frame line-240 interrupt.
    pub irq: bool,
    /// ROM PIA CB1: the four-times-per-frame, approximately 4 ms interrupt.
    pub firq: bool,
}

/// The early Williams/Stargate main-board address space.
pub struct StargateBus {
    rom: [u8; 0x1_0000],
    vram: [u8; 0xc000],
    cmos: [u8; 0x0400],
    palette: [u8; 0x0010],
    /// 6821 registers in MAME `pia6821_device` order, per PIA:
    /// `[0]` = port A data, `[1]` = control A, `[2]` = port B data,
    /// `[3]` = control B.
    pia: [[u8; 4]; 2],
    /// 6821 CA1/CB1 interrupt flags (bit 7 of the control register).
    pia_irq_a1: [bool; 2],
    pia_irq_b1: [bool; 2],
    /// Current level of the CA1/CB1 input lines (for edge detection).
    pia_line_ca1: [bool; 2],
    pia_line_cb1: [bool; 2],
    bank_rom: bool,
    /// RWCNTL bit 1: cocktail table screen inversion (stored for parity
    /// with MAME's `vram_select_w`; the upright bitmap is not flipped).
    cocktail: bool,
    watchdog_writes: u64,
    input: StargateInput,
    sound_commands: Vec<u8>,
    video_frame: Vec<u8>,
    video_cycles: u64,
    video_scanline: usize,
    /// Debug hook: PC/instruction count of the instruction currently being
    /// executed (set by `StargateMachine::step` before each step).
    pub debug_pc: u16,
    pub debug_instr: u64,
}

impl StargateBus {
    pub fn from_rom_dir(dir: &Path) -> Result<Self, Box<dyn std::error::Error>> {
        let mut bus = Self {
            rom: [0; 0x1_0000],
            vram: [0; 0xc000],
            cmos: [0; 0x0400],
            palette: [0; 0x0010],
            pia: [[0; 4]; 2],
            pia_irq_a1: [false; 2],
            pia_irq_b1: [false; 2],
            pia_line_ca1: [false; 2],
            pia_line_cb1: [false; 2],
            bank_rom: false,
            cocktail: false,
            watchdog_writes: 0,
            input: StargateInput::default(),
            sound_commands: Vec::new(),
            video_frame: vec![0; 292 * 240 * 4],
            video_cycles: 0,
            video_scanline: 0,
            debug_pc: 0,
            debug_instr: 0,
        };
        for (address, name) in ROMS {
            let data = fs::read(dir.join(name))?;
            if data.len() != 0x1000 {
                return Err(format!("ROM {name} is {} bytes, expected 4096", data.len()).into());
            }
            bus.rom[address as usize..address as usize + data.len()].copy_from_slice(&data);
        }
        Ok(bus)
    }

    /// Render the Williams packed 4-bit video RAM as a terminal-friendly
    /// luminance image. Each video byte contains two horizontal pixels and
    /// rows are separated by 256 bytes.
    pub fn video_ascii(&self, columns: usize, rows: usize) -> Vec<String> {
        const RAMP: &[u8] = b" .:-=+*#%@";
        (0..rows)
            .map(|out_y| {
                let y = out_y * 240 / rows;
                (0..columns)
                    .map(|out_x| {
                        let x = out_x * 304 / columns;
                        let packed = self.vram[y + (x / 2) * 256];
                        let pixel = if x & 1 == 0 {
                            packed >> 4
                        } else {
                            packed & 0x0f
                        };
                        RAMP[(pixel as usize * (RAMP.len() - 1) / 15).min(RAMP.len() - 1)] as char
                    })
                    .collect()
            })
            .collect()
    }

    /// Return the visible framebuffer as RGBA pixels for graphical frontends.
    pub fn video_rgba(&self) -> Vec<u8> {
        let mut pixels = Vec::with_capacity(304 * 240 * 4);
        for y in 0..240 {
            for x in 0..304 {
                let packed = self.vram[y + (x / 2) * 256];
                let value = if x & 1 == 0 {
                    packed >> 4
                } else {
                    packed & 0x0f
                };
                pixels.extend_from_slice(&Self::palette_rgba(self.palette[value as usize]));
            }
        }
        pixels
    }

    /// Render Stargate's MAME-visible area (x=12..303, y=7..246).
    pub fn video_rgba_visible(&self) -> Vec<u8> {
        self.video_frame.clone()
    }

    /// Advance the raster beam. Stargate's 1 MHz 6809 and 512x260 video
    /// timing yield exactly 64 CPU cycles per scanline.
    pub fn advance_video(&mut self, cycles: u64) -> VideoInterrupts {
        let mut interrupts = VideoInterrupts::default();
        self.video_cycles += cycles;
        while self.video_cycles >= 64 {
            self.video_cycles -= 64;
            let scanline = self.video_scanline;
            self.render_scanline(scanline);
            // Beam-position lines into ROM PIA 1 (MAME williams_m.cpp
            // va11_callback / count240_callback):
            //   CB1 = VA11 = bit 5 of the scanline counter (toggles every
            //         32 lines); MAME suppresses the callback at line 256.
            //   CA1 = COUNT240 = high from line 240 on (once per frame).
            if scanline != 256 {
                self.set_cb1(1, (scanline >> 5) & 1 == 1);
            }
            self.set_ca1(1, scanline >= 240);
            self.video_scanline = (self.video_scanline + 1) % 260;
        }
        // The 6821 asserts its IRQ output while (flag && enable); the
        // 6809's IRQ vector ($FFF8/$FFF9) is $9C6B (the beam handler).
        interrupts.irq = self.pia_irq_level();
        interrupts
    }

    /// Drive the CA1 line of PIA `p`, latching the 6821 IRQA1 flag on the
    /// active edge (control bit 1: 1 = low->high, 0 = high->low).
    fn set_ca1(&mut self, p: usize, state: bool) {
        if self.pia_line_ca1[p] != state {
            let active_rising = self.pia[p][1] & 0x02 != 0;
            if state == active_rising {
                self.pia_irq_a1[p] = true;
            }
            self.pia_line_ca1[p] = state;
        }
    }

    /// Drive the CB1 line of PIA `p` (see `set_ca1` for semantics).
    fn set_cb1(&mut self, p: usize, state: bool) {
        if self.pia_line_cb1[p] != state {
            let active_rising = self.pia[p][3] & 0x02 != 0;
            if state == active_rising {
                self.pia_irq_b1[p] = true;
            }
            self.pia_line_cb1[p] = state;
        }
    }

    /// 6821 IRQ output: asserted while a CA1/CB1 flag is set and the
    /// corresponding interrupt-enable bit (control bit 0) is set.
    fn pia_irq_level(&self) -> bool {
        (0..2).any(|p| {
            (self.pia_irq_a1[p] && self.pia[p][1] & 0x01 != 0)
                || (self.pia_irq_b1[p] && self.pia[p][3] & 0x01 != 0)
        })
    }

    fn render_scanline(&mut self, scanline: usize) {
        // Stargate's visible area is x=6..297, y=7..246 (base platform
        // default). Defender uses 12..303 and is not rendered here.
        if !(7..247).contains(&scanline) {
            return;
        }
        let row = scanline - 7;
        let start = row * 292 * 4;
        for x in 6..298 {
            let packed = self.vram[scanline + (x / 2) * 256];
            let value = if x & 1 == 0 {
                packed >> 4
            } else {
                packed & 0x0f
            };
            let pixel = Self::palette_rgba(self.palette[value as usize]);
            let offset = start + (x - 6) * 4;
            self.video_frame[offset..offset + 4].copy_from_slice(&pixel);
        }
    }

    fn palette_rgba(value: u8) -> [u8; 4] {
        let component =
            |bits: u8| -> u8 { [0x00, 0x26, 0x51, 0x76, 0x89, 0xae, 0xd9, 0xff][bits as usize] };
        let blue = ((if value & 0x40 != 0 { 0x5f } else { 0 })
            + if value & 0x80 != 0 { 0xa0 } else { 0 }) as u8;
        [component(value & 7), component((value >> 3) & 7), blue, 255]
    }

    fn pia_index(addr: usize) -> Option<(usize, usize)> {
        match addr {
            0xc804..=0xc807 => Some((0, addr - 0xc804)),
            0xc80c..=0xc80f => Some((1, addr - 0xc80c)),
            _ => None,
        }
    }

    fn read_mapped(&self, addr: usize) -> u8 {
        match addr {
            0x0000..=0x8fff if self.bank_rom => self.rom[addr],
            0x0000..=0xbfff => self.vram[addr],
            0xc000..=0xc00f => 0, // write-only palette
            0xc804..=0xc807 | 0xc80c..=0xc80f => {
                let (pia, reg) = Self::pia_index(addr).unwrap();
                match reg {
                    // Port A data: the value; flag clear happens on the
                    // real read path (load_byte), not here.
                    0 => match (pia, reg) {
                        (0, 0) => self.input.port0(),
                        (1, 0) => self.input.port2(),
                        _ => self.pia[pia][reg],
                    },
                    // Port B data.
                    2 => match (pia, reg) {
                        (0, 2) => self.input.port1(),
                        _ => self.pia[pia][reg],
                    },
                    // Control registers: bit 7/6 report the CA1/CB1 flags.
                    1 => self.pia[pia][1] | (self.pia_irq_a1[pia] as u8) << 7,
                    3 => self.pia[pia][3] | (self.pia_irq_b1[pia] as u8) << 7,
                    _ => self.pia[pia][reg],
                }
            }
            0xcb00..=0xcbff => {
                // Vertical beam counter: 6 bits of vpos (bits 2-7); MAME
                // returns vpos & 0xfc, and 0xfc for lines >= 256.
                let v = self.video_scanline;
                (if v < 0x100 { v & 0xfc } else { 0xfc }) as u8
            }
            0xcc00..=0xcfff => self.cmos[addr - 0xcc00],
            0xd000..=0xffff => self.rom[addr],
            _ => 0,
        }
    }

    /// Load a CMOS/nvram image (MAME `nvram` file: 1024 bytes, CMOS
    /// address `CC00+offset`) into the battery-backed RAM.
    pub fn load_nvram(&mut self, data: &[u8]) {
        let n = data.len().min(self.cmos.len());
        self.cmos[..n].copy_from_slice(&data[..n]);
    }

    /// Return a copy of the CMOS image (MAME `nvram` file format).
    pub fn save_nvram(&self) -> Vec<u8> {
        self.cmos.to_vec()
    }

    pub fn set_input(&mut self, input: StargateInput) {
        self.input = input;
    }

    pub fn take_sound_commands(&mut self) -> Vec<u8> {
        std::mem::take(&mut self.sound_commands)
    }

    pub fn palette(&self) -> [u8; 16] {
        self.palette
    }

    /// Current beam scanline (0..260) for diagnostics.
    pub fn video_scanline(&self) -> usize {
        self.video_scanline
    }
}

impl MemoryIO for StargateBus {
    fn inspect_byte(&self, addr: usize) -> MemResult<u8> {
        if addr < 0x1_0000 {
            Ok(self.read_mapped(addr))
        } else {
            Err(MemErrorTypes::IllegalAddress(addr))
        }
    }
    fn inspect_word(&self, addr: usize) -> MemResult<u16> {
        Ok(u16::from_be_bytes([
            self.inspect_byte(addr)?,
            self.inspect_byte(addr + 1)?,
        ]))
    }
    fn upload(&mut self, addr: usize, data: &[u8]) -> MemResult<()> {
        for (offset, value) in data.iter().enumerate() {
            self.store_byte(addr + offset, *value)?;
        }
        Ok(())
    }
    fn get_range(&self) -> std::ops::Range<usize> {
        0..0x1_0000
    }
    fn update_sha1(&self, digest: &mut Sha1) {
        digest.update(self.rom);
        digest.update(self.vram);
        digest.update(self.cmos);
    }
    fn load_byte(&mut self, addr: usize) -> MemResult<u8> {
        // 6821 side effect: reading a port data register clears the
        // corresponding CA1/CB1 interrupt flag.
        if let Some((pia, reg)) = Self::pia_index(addr) {
            if reg == 0 {
                self.pia_irq_a1[pia] = false;
            } else if reg == 2 {
                self.pia_irq_b1[pia] = false;
            }
        }
        self.inspect_byte(addr)
    }
    fn store_byte(&mut self, addr: usize, value: u8) -> MemResult<()> {
        if addr >= 0x1_0000 {
            return Err(MemErrorTypes::IllegalAddress(addr));
        }
        match addr {
            0x0000..=0xbfff => self.vram[addr] = value,
            0xc000..=0xc00f => self.palette[addr - 0xc000] = value,
            0xc804..=0xc807 | 0xc80c..=0xc80f => {
                let (pia, reg) = Self::pia_index(addr).unwrap();
                self.pia[pia][reg] = value;
                // PIA 1 port B is the main-to-sound command latch. Williams
                // drives the upper two bits high before pulsing CB1.
                if pia == 1 && reg == 2 {
                    self.sound_commands.push(value | 0xc0);
                }
            }
            0xc900..=0xc9ff => {
                self.bank_rom = value & 1 != 0;
                self.cocktail = value & 2 != 0;
            }
            0xcbff => {
                if value == 0x39 {
                    self.watchdog_writes += 1;
                }
            }
            0xcc00..=0xcfff => {
                // Battery-backed 4-bit CMOS: MAME's williams driver stores
                // writes with the upper nibble forced to ones (only 4 bits
                // are valid), which games rely on in read-modify-write.
                self.cmos[addr - 0xcc00] = value | 0xf0
            }
            0xd000..=0xffff => {} // ROM / unmapped writes are ignored
            _ => {}
        }
        Ok(())
    }
    fn store_word(&mut self, addr: usize, value: u16) -> MemResult<()> {
        let [hi, lo] = value.to_be_bytes();
        self.store_byte(addr, hi)?;
        self.store_byte(addr + 1, lo)
    }
    fn load_word(&mut self, addr: usize) -> MemResult<u16> {
        Ok(u16::from_be_bytes([
            self.load_byte(addr)?,
            self.load_byte(addr + 1)?,
        ]))
    }
}

#[cfg(test)]
mod tests {
    use super::StargateBus;
    use crate::StargateInput;
    use emucore::mem::MemoryIO;

    fn bus() -> StargateBus {
        StargateBus {
            rom: [0; 0x1_0000],
            vram: [0; 0xc000],
            cmos: [0; 0x0400],
            palette: [0; 0x0010],
            pia: [[0; 4]; 2],
            pia_irq_a1: [false; 2],
            pia_irq_b1: [false; 2],
            pia_line_ca1: [false; 2],
            pia_line_cb1: [false; 2],
            bank_rom: false,
            cocktail: false,
            watchdog_writes: 0,
            input: StargateInput::default(),
            sound_commands: Vec::new(),
            video_frame: vec![0; 292 * 240 * 4],
            video_cycles: 0,
            video_scanline: 0,
            debug_pc: 0,
            debug_instr: 0,
        }
    }

    #[test]
    fn bank_select_changes_low_memory_reads_but_not_writes() {
        let mut bus = bus();
        bus.rom[0x1234] = 0xa5;
        bus.store_byte(0x1234, 0x5a).unwrap();
        assert_eq!(bus.load_byte(0x1234).unwrap(), 0x5a);
        bus.store_byte(0xc900, 1).unwrap();
        assert_eq!(bus.load_byte(0x1234).unwrap(), 0xa5);
        bus.store_byte(0x1234, 0x3c).unwrap();
        bus.store_byte(0xc900, 0).unwrap();
        assert_eq!(bus.load_byte(0x1234).unwrap(), 0x3c);
    }

    #[test]
    fn watchdog_only_accepts_stargate_reset_value() {
        let mut bus = bus();
        bus.store_byte(0xcbff, 0).unwrap();
        bus.store_byte(0xcbff, 0x39).unwrap();
        assert_eq!(bus.watchdog_writes, 1);
    }

    #[test]
    fn pia_reads_follow_logical_inputs() {
        let mut bus = bus();
        bus.set_input(StargateInput {
            fire: true,
            down: true,
            coin1: true,
            ..Default::default()
        });
        assert_eq!(bus.load_byte(0xc804).unwrap(), 0x81);
        assert_eq!(bus.load_byte(0xc806).unwrap(), 0x00);
        assert_eq!(bus.load_byte(0xc80c).unwrap(), 0x10);
    }
}
